### ISSUE TITLE
Stripping comments

### ISSUE THREAD

**Issue by KnorpelSenf** [wojpawlik/deno2node#10]
It seems like `deno2node` strips comments and JSDoc. It therefore removes the documentation of the library. Is this intended?

Tried with
```bash
deno run --unstable --allow-read --allow-write \
  https://raw.githubusercontent.com/wojpawlik/deno2node/v0.4.0/src/cli.ts tsconfig.json
```
for [grammY runner](https://github.com/grammyjs/runner).

**Comment by wojpawlik** [comment]
https://github.com/grammyjs/runner/blob/0dbd8ef22d347e16424a1dbc5f320459d32ee42f/tsconfig.json#L15, https://github.com/microsoft/TypeScript/issues/14619

**Comment by KnorpelSenf** [comment]
Wow … I need new glasses, thanks
