### ISSUE TITLE
Examples in README do not work

### ISSUE THREAD

**Issue by KnorpelSenf** [wojpawlik/deno2node#3]
Tried to run the CLI using Deno on the project itself.

1. Clone this repo, and `cd` into it.
2. Run:

```
$ deno run --unstable --allow-read --allow-write https://raw.githubusercontent.com/wojpawlik/deno2node/v0.2.0/src/cli.ts src/tsconfig.json 
Download https://cdn.esm.sh/v41/validate-npm-package-name@3.0.0/deno/validate-npm-package-name.js
error: Import 'https://cdn.esm.sh/v41/validate-npm-package-name@3.0.0/deno/validate-npm-package-name.js' failed: 404 Not Found
    at https://esm.sh/validate-npm-package-name@3.0.0:2:0
```

Same error occurs when running `npm i` in the top level directory of this project.

**Comment by wojpawlik** [comment]
Works for me, try `--reload`ing.

**Comment by KnorpelSenf** [comment]
I did that yesterday with the same result.

I did it today again, and now esm.sh does not 404 anymore. Who knows what had happened there … thanks :+1:
