### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by KnorpelSenf** [wojpawlik/deno2node#5]
It would be cool to have a brief overview in the README file about the following things:
1. How does the tool even work in the first place, i.e. what does it do, and what is it build on?
2. Should I use the CLI, or a programmatic API?
3. What does the tool assert about my library (folder structure)?
4. What is the API?
5. How to use the CLI?

Some of these things are pretty obvious to answer by reading the source code for a few minutes. However, as time goes by and deno2node gets more complex, these things will become less and less clear for new users.

**Comment by wojpawlik** [comment]
> 2. Should I use the CLI, or a programmatic API?

Whichever better fits the task at hand.

> 4. What is the API?

<a href="https://doc.deno.land/https/raw.githubusercontent.com/wojpawlik/deno2node/main/src/mod.ts"><img src="https://doc.deno.land/badge.svg" alt="deno doc"></a>

> 5. How to use the CLI?

https://github.com/wojpawlik/deno2node#usage-from-nodejs

**Comment by wojpawlik** [comment]
> 1. How does the tool even work in the first place, i.e. what does it do

https://github.com/wojpawlik/deno2node/blob/d224750108fcdc70d666b3cc3f9e95e6310a4a47/src/deno2node.ts#L45-L65

> what is it build on?

https://github.com/wojpawlik/deno2node/blob/d224750108fcdc70d666b3cc3f9e95e6310a4a47/package.json#L46 https://github.com/wojpawlik/deno2node/blob/d224750108fcdc70d666b3cc3f9e95e6310a4a47/src/deps.deno.ts#L4

> 3. What does the tool assert about my library (folder structure)?

- `deno2node` needs `tsconfig.json`,
- `deno2node` needs an output directory for emitting, just like `tsc`,
- Platform-specific code needs to live in separate files next to each other (`deps.deno.ts`, `deps.node.ts`).

**Comment by wojpawlik** [comment]
I wanted to write more about the API, but frankly I'm not sure how to best use it. I believe I addressed everything else.
