### ISSUE TITLE
Node deps are published at deno.land/x

### ISSUE THREAD

**Issue by KnorpelSenf** [wojpawlik/deno2node#6]
`deno2node` requires the code base for Deno and Node to be in a shared location, effectively interleaving the files. This leads to `deps.node.ts` being published, as can be observed for <https://deno.land/x/grammy_router>. It is preferable to only publish those files to <https://deno.land/x> that actually are part of the Deno source code.

Is there any way around this, maybe by moving the `deps.node.ts` file outside of the repository's subdirectory that gets published at deno.land?

**Comment by wojpawlik** [comment]
> moving the `deps.node.ts` file outside of the repository's subdirectory that gets published at deno.land?

That'd make project structure way messier...

From my PoV, this is caused by lack of `.denolandxignore`.

**Comment by KnorpelSenf** [comment]
Confer https://github.com/denoland/deno_website2/issues/1748
